"""Created Profile and User tables

Revision ID: 1c8676b752ee
Revises: 
Create Date: 2024-05-22 23:56:36.181901

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1c8676b752ee"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("users_username_key", "users", type_="unique")
    op.create_unique_constraint(
        op.f("uq_users_username"), "users", ["username"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_users_username"), "users", type_="unique")
    op.create_unique_constraint("users_username_key", "users", ["username"])
    # ### end Alembic commands ###
